### ISSUE TITLE
That's not a issue I want to tell you something on my side.

### ISSUE THREAD

**Issue by mygitrepo510k** [OpenNebula/addon-nodejs#7]
First of all, your plugin is amazing. :smile:
But I have one issue.
```
var vm = aa.getVM(1);
vm.chmod(1,1,1,-1,-1,-1,-1,-1,-1, function(err, data){
console.log(err);
console.log(data);
});
```
I got this error.
```
{ Error: XML-RPC fault: Parameter that is supposed to be boolean is not
    at createFault (/home/osboxes/aaa/node_modules/xmlrpc/lib/deserializer.js:82:21)
    at Deserializer.onDone (/home/osboxes/aaa/node_modules/xmlrpc/lib/deserializer.js:88:21)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (/home/osboxes/aaa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/home/osboxes/aaa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/home/osboxes/aaa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at Object.end (/home/osboxes/aaa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/home/osboxes/aaa/node_modules/xmlrpc/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (_stream_readable.js:511:10)
  code: -501,
  faultCode: -501,
  faultString: 'Parameter that is supposed to be boolean is not' }

```
Please help me!!!

**Comment by apocas** [comment]
Actually it may be an issue :)

VM.chmod was missing a new boolean parameter.
http://docs.opennebula.org/5.4/integration/system_interfaces/api.html#one-template-chmod
"true to chmod the template plus any image defined in DISK."

Just published a new version (v1.0.11) update and test again :)

**Comment by feldsam** [comment]
this looks like fixed, so should be closed. @mygitrepo510k can you confirm?
